dependencies:
  - bokeh::bokeh=1.1.0
  - matplotlib
  - nbserverproxy
  - numpy
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz/label/dev::holoviews=1.12.2
  - pyviz/label/dev::panel=0.5.1
  - sparse
  - tornado <6
